#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hook"

echo "Running lint-staged"
npx lint-staged

echo "Update version"
npm --no-git-tag-version version patch && git add .